apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongo-nodeport-svc
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 32001
  selector:
    app: mongodb
  type: NodePort
